version: '3.5'
services:
  postgres:
    image: "postgres:15-bullseye"
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports: 5432:5432
  adminer:
    image: adminer
    ports: 8080:8080